---

- hosts: apt,dnf
  become: true
  pre_tasks:

  - name: install updates (debain, ubuntu & centos)
    package:
      update_cache: yes

- hosts: dnf
  become: true
  pre_tasks:

  - name: install epel-release (centos)
    package:
      name:
        - epel-release
      state: latest

- hosts: apt,dnf
  become: true
  tasks:

  - name: install htop, neofetch, ncdu, vim & tmux (debian, ubuntu & centos)
    package:
      name:
        - htop
        - neofetch
        - ncdu
        - vim
        - tmux
      state: latest
